export const SET_DATA = 'SET_DATA';
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const DATA_LOADED = 'DATA_LOADED';
export const DATA_REQUESTED = 'DATA_REQUESTED';
 
// Authentication Constants 
export const SUCCESSFULL_AUTHENTICATION = 'SUCCESSFULL_AUTHENTICATION';
export const FAILED_AUTHENTICATION = 'FAILED_AUTHENTICATION';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CLEAN_AUTHENTICATION = 'CLEAN_AUTHENTICATION';

// Constants of Course
export const SUCCESSFULL_NEW_COURSE='SUCCESSFULL_NEW_COURSE';
export const FAILED_NEW_COURSE='FAILED_NEW_COURSE';
export const SAVE_COURSE = 'SAVE_COURSE';

// Constants of Programmbs
export const SHOW_PROGRAMMBS="SHOW_PROGRAMMBS";
export const UPDATE_REVISION_PROGRAMMBS="UPDATE_REVISION_PROGRAMMBS";
export const LOAD_FORM_PROGRAMMBS="LOAD_FORM_PROGRAMMBS";
export const ERROR_EDIT_REVISION="FAILED_EDIT_REVISION";
export const SUCCESSFULL_EDIT_REVISION="SUCCESSFULL_EDIT_REVISION";
export const HIDE_REVISION_ALERT="HIDE_REVISION_ALERT";
export const SUCCESSFULL_APPROVE_PROJECT="SUCCESSFULL_APPROVE_PROJECT";
export const ERROR_APPROVE_PROJECT="ERROR_APPROVE_PROJECT";
export const SUCCESSFULL_SEND_REVISION_PROJECT="SUCCESSFULL_SEND_REVISION_PROJECT";
export const ERROR_SEND_REVISION_PROJECT="ERROR_SEND_REVISION_PROJECT";
export const ACTIVE_TAB="ACTIVE_TAB";
export const RESET_SHOW_PROGRAMMBS="RESET_SHOW_PROGRAMMBS";

// Constants of Programsa
export const SHOW_PROGRAMSA="SHOW_PROGRAMSA";
export const UPDATE_REVISION_PROGRAMSA="UPDATE_REVISION_PROGRAMSA";
export const LOAD_FORM_PROGRAMSA="LOAD_FORM_PROGRAMSA";



// Constants of Student
export const STUDENT_LIST="STUDENT_LIST";
export const MBS_STUDENT_LIST="MBS_STUDENT_LIST";
export const SHOW_STUDENT="SHOW_STUDENT";
export const LOAD_FORM_STUDENT="LOAD_FORM_STUDENT";
export const EDIT_STUDENT="EDIT_STUDENT";
export const NEW_STUDENT="NEW_STUDENT";
export const ERROR_EDIT_STUDENT="ERROR_EDIT_STUDENT";
export const DELETE_STUDENT="DELETE_STUDENT";
export const EDIT_PASSWORD_STUDENT="EDIT_PASSWORD_STUDENT"
export const GET_STUDENT_AMBASSADOR="GET_STUDENT_AMBASSADOR"

// Constants of User
export const SHOW_USER="SHOW_USER";
export const LOAD_FORM_USER="LOAD_FORM_USER";
export const EDIT_USER="EDIT_USER";
export const DELETE_USER="DELETE_USER";
export const EDIT_PASSWORD_USER="EDIT_PASSWORD_USER";
export const ERROR_EDIT_USER="ERROR_EDIT_USER";
export const SUCCESSFULL_ACTIVE_USER="SUCCESSFULL_ACTIVE_USER";
export const NEW_PASSWORD="NEW_PASSWORD";
export const ERROR_GMAIL="ERROR_GMAIL";

// General Constants 
export const SUCCESSFULL_EDIT="SUCCESSFULL_EDIT";
export const SUCCESSFULL_NEW="SUCCESSFULL_NEW";
export const SUCCESSFUL_DELETE="SUCCESSFUL_DELETE";
export const ERROR_REQUIRED_FIELDS="ERROR_REQUIRED_FIELDS";
export const SUCCESS_REQUIRED_FIELDS="SUCCESS_REQUIRED_FIELDS";
export const COUNTRY_LIST="COUNTRY_LIST";
export const DISMATCH_PASSWORD= "DISMATCH_PASSWORD";
export const DELETE_SUCCESSFUL ="DELETE_SUCCESSFUL";
export const SUCCESSFULL_EDIT_CLEAN="SUCCESSFULL_EDIT_CLEAN";
export const UPDATE_FILE_NAME="UPDATE_FILE_NAME";
export const DELETE_ALERT="DELETE_ALERT"
export const REDIRECT_GROUP= "REDIRECT_GROUP"
export const SUCCESSFULL_REDIRECT="SUCCESSFULL_REDIRECT"

// Select Constans 
export const UPDATE_LANGUAGE_SELECT="UPDATE_LANGUAGE_SELECT";
export const UPDATE_PROGRAM_SELECT="UPDATE_PROGRAM_SELECT";
export const UPDATE_MODALITY_SELECT="UPDATE_MODALITY_SELECT";
export const UPDATE_ROLE_SELECT="UPDATE_ROLE_SELECT";
export const UPDATE_COUNTRY_SELECT="UPDATE_COUNTRY_SELECT";
export const UPDATE_AMBASSADOR_SELECT="UPDATE_AMBASSADOR_SELECT";
export const UPDATE_QUALITY1_SELECT="UPDATE_QUALITY1_SELECT";

// Constants of Group
export const GROUP_LIST="GROUP_LIST";
export const LOAD_FORM_GROUP="LOAD_FORM_GROUP";
export const SHOW_GROUP="SHOW_GROUP";
export const EDIT_GROUP="EDIT_GROUP";
export const NEW_GROUP="NEW_GROUP";
export const DELETE_GROUP="DELETE_GROUP";
export const DEFAULT_FORM_GROUP="DEFAULT_FORM_GROUP";
export const GET_AMBASSADOR_ID="GET_AMBASSADOR_ID";
export const GET_PROJECT_PROGRESS="GET_PROJECT_PROGRESS";
export const MBS_IMAGE_ALERT="MBS_IMAGE_ALERT";
export const UPLOAD_IMAGE="UPLOAD_IMAGE";
export const DELETE_IMAGE_ALERT="DELETE_IMAGE_ALERT";
export const GROUP_PROGRAM="GROUP_PROGRAM";

// Constants of Ambassador 
export const AMBASSADOR_LIST = "AMBASSADOR_LIST";
export const SHOW_AMBASSADOR="SHOW_AMBASSADOR";
export const LOAD_FORM_AMBASSADOR="LOAD_FORM_AMBASSADOR";
export const EDIT_AMBASSADOR="EDIT_AMBASSADOR";
export const ERROR_EDIT_AMBASSADOR="ERROR_EDIT_AMBASSADOR";
export const NEW_AMBASSADOR="NEW_AMBASSADOR";
export const EDIT_PASSWORD_AMBASSADOR="EDIT_PASSWORD_AMBASSADOR";
export const DELETE_AMBASSADOR="DELETE_AMBASSADOR";

// Constants of Certificate 
export const GET_CERTIFICATE_LIST= "GET_CERTIFICATE_LIST";

// Constants of Dashboard
export const STUDENT_MBS_LIST = "STUDENT_MBS_LIST";
export const STUDENT_AMBASSADOR_LIST = "STUDENT_AMBASSADOR_LIST";
export const FUTURE_AMBASSADOR_LIST = "FUTURE_AMBASSADOR_LIST";
export const DASHBOARD_STUDENT = "DASHBOARD_STUDENT";
export const AMBASSADOR_STUDENT_LIST="AMBASSADOR_STUDENT_LIST";

//Constants of Reports
export const GET_REPORTS = "GET_REPORTS";
export const GET_REPORT_COUNTRY = "GET_REPORT_COUNTRY";
export const GET_REPORT_AMBASSADOR = "GET_REPORT_AMBASSADOR";
export const GET_AMBASSADOR_COUNTRY = "GET_AMBASSADOR_COUNTRY";
export const AMBASSADOR_REPORT = "AMBASSADOR_REPORT";
export const GET_REPORT_GLOBAL_MAP = "GET_REPORT_GLOBAL_MAP";
export const GET_GLOBAL_NUMBERS = "GET_GLOBAL_NUMBERS";

//Constants of Code
export const CODE_LIST="CODE_LIST";
export const SHOW_CODE="SHOW_CODE";
export const LOAD_FORM_CODE="LOAD_FORM_CODE";
export const EDIT_CODE="EDIT_CODE";
export const ERROR_EDIT_CODE="ERROR_EDIT_CODE";
export const DELETE_CODE="DELETE_CODE";

//Constants of Administrator
export const ADMINISTRATOR_LIST="ADMINISTRATOR_LIST";
export const ADMINLANGUAGE_LIST="ADMINLANGUAGE_LIST";
export const NEW_ADMINISTRATOR="NEW_ADMINISTRATOR";
export const SHOW_ADMINISTRATOR="SHOW_ADMINISTRATOR";
export const LOAD_FORM_ADMINISTRATOR="LOAD_FORM_ADMINISTRATOR";
export const EDIT_ADMINISTRATOR="EDIT_ADMINISTRATOR";
export const ERROR_EDIT_ADMINISTRATOR="ERROR_EDIT_ADMINISTRATOR";
export const EDIT_PASSWORD_ADMINISTRATOR="EDIT_PASSWORD_ADMINISTRATOR";
export const DELETE_ADMINISTRATOR = "DELETE_ADMINISTRATOR";

//Constants of Evaluation
export const EVALUATION_PRE="EVALUATION_PRE";
export const EVALUATION_POST="EVALUATION_POST";
export const PRE_ALERT="PRE_ALERT";
export const POST_ALERT="POST_ALERT";
export const SHOW_EVALUATION="SHOW_EVALUATION";
export const LOAD_FORM_EVALUATION="LOAD_FORM_EVALUATION";

